import type { Metadata } from "next";
// import { Poppins } from "next/font/google";
import { Inter } from 'next/font/google';
import "../globals.css"
import { SidebarProvider, SidebarTrigger } from '@/components/ui/sidebar'
import { AppSidebar } from '@/components/layouts/sidebar'
import { AppNavbar } from '@/components/layouts/navbar'
import { AppContent } from '@/components/layouts/content'

const inter = Inter({
    subsets: ['latin'],
    variable: '--font-inter',
})
// const poppins = Poppins({
//   subsets: ['latin'],
//   weight: ['400', '500', '600', '700'], // sesuaikan kebutuhanmu
//   variable: '--font-poppins',
//   display: 'swap',
// })

export const metadata: Metadata = {
    title: "Web Panel | My-POS",
    description: "Generated by create next app",
};

export default function Layout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (

        <html lang="en">
            <body
                className={`${inter.className}`}
            >
                <SidebarProvider>
                    <AppSidebar />
                    <main className="w-full">
                        <AppNavbar />
                        <AppContent>
                            {children}
                        </AppContent>
                    </main>
                </SidebarProvider>
            </body>
        </html>
    );
}
