import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { SidebarProvider, SidebarTrigger } from '@/components/ui/sidebar'

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'], // sesuaikan kebutuhanmu
  variable: '--font-poppins',
  display: 'swap',
})

export const metadata: Metadata = {
    title: "Web Panel | My-POS",
    description: "Generated by create next app",
};

export default function Layout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <SidebarProvider>
            <html lang="en">
                <body
                    className={`${poppins.className}`}
                >
                    {children}
                </body>
            </html>
        </SidebarProvider>
    );
}
